### ISSUE TITLE
Add getRegisteredCultures() function in public SFFJS API

### ISSUE THREAD

**Issue by Maxoudela** [dmester/sffjs#10]
Hi,

First of all, thank you for your work. I'm discovering SFFJS and I really like what I see. 

I stumbled across a minor issue, it seems that there is no public API for accessing the registered cultures. Is there a reason for that? Would you consider adding such API?

I can, of course, provide a pull request if interested on which we could talk implementation details.

Regards,

**Comment by dmester** [comment]
Hello,

The main reason is that I've considered the culture objects as an implementation detail. They are not very public API friendly in their current implementation.

What is the use case you need it for? Just getting a list of registered culture codes or also using the actual culture objects?

**Comment by Maxoudela** [comment]
Hi,

For my specific use-case, I only need the culture name in fact. I extract all the names from the registered cultures, then when my locale changes in my app from "en-us" to "fr-ca" for example (Canadian French), I'm able to give the requested language and all the available SFFJS languages to an algorithm that does a "best match".

Therefore, if "fr-ca" is not available but I have a basic french culture registered ("fr"), I'll use this one.

The second use-case (But I wanted to create another issue for that one), is to add an API for accessing the current culture, or at least the current culture name, thousand separator and decimal separator. 

- For the name, it's simply in order to verify that the setCulture has actually worked.
- For the separators, when a user is editing numbers in my app, I need to replace some of the separators before parsing the numbers. For example, a french user will input "200,3" for the number "200.3" and I need to replace the comma with a dot. That's a bit out of SFFJS scope but since SFFJS has these information, it could be useful to have access to them.

Let me know if this makes sense,

**Comment by dmester** [comment]
Thanks for the detailed use cases!

The current culture is already accessible from the property `sffjs.LC`. It was previously not documented, but now it is mentioned on the page [Working with cultures](https://github.com/dmester/sffjs/blob/master/docs/Working%20with%20cultures.md) and included in the TypeScript typings.

You can reach the decimal separator by `sffjs.LC._r` and thousands separator by `sffjs.LC._t`.

I have also added the method `sffjs.getCultures()`, which will return all culture objects, including the invariant culture. My initial thought was to make the property naming more human readable, but since the culture was already exposed by the `LC` property, this could not be done in a good way without introducing a breaking change.

**Comment by Maxoudela** [comment]
Thank you very much for your reactivity and pushing these changes. I've tested them in my app and it's working perfectly. 

(We are using Typescript and we have some issues integrating SFFJS, I might be coming back with another issue but I'll triple-check with my team before opening an issue in order not to waste your time.)
