### ISSUE TITLE
Percent format specifier is not implemented

### ISSUE THREAD

**Issue by Atrejoe** [dmester/sffjs#8]
It appears that the percent format specifier is not implemented:

See specifications:
https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-numeric-format-strings#the-percent-p-format-specifier

#### What it should do:
```C#
var value = 1.912421m;

$"{value:p}".Dump();
$"{value:p0}".Dump();
$"{value:p10}".Dump();
```

values:
```
191,24%
191%
191,2421000000%
```
#### What it does:
*Values are not multiplied by 100*
```
1,91%
2%
1,9124210000%
```
#### Workaround
Use [custom format string `%`](https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-numeric-format-strings#the--custom-specifier-3)
`#.## %` instead of `p2`

**Comment by dmester** [comment]
Thanks for opening this issue. The percent format specifier is implemented since version 1.04 of sffjs and I'm afraid I'm unable to reproduce the issue. Are you sure you are using the latest version? If so, please provide a code snippet for reproducing the issue.

This is what I tested.

## Sffjs v 1.16 ([run code](https://jsfiddle.net/g48vtbmy/))
```js
String.format("{0:p}", 1.912421);
String.format("{0:p0}", 1.912421);
String.format("{0:p10}", 1.912421);
```

Output
```
191.24 %
191 %
191.2421000000 %
```

## .NET Framework ([run code](https://dotnetfiddle.net/ckVcuy))
```cs
Console.WriteLine("{0:p}", 1.912421m);
Console.WriteLine("{0:p0}", 1.912421m);
Console.WriteLine("{0:p10}", 1.912421m);
```

Output
```
191.24 %
191 %
191.2421000000 %
```
